export type CountryCode = {
  name: string;
  code: string;
};

// Data collected from https://help.marinetraffic.com/hc/en-us/articles/360018392858-How-does-MarineTraffic-identify-a-vessel-s-country-and-flag-
export const countryTable = new Map<string, CountryCode>([
  ['201', { name: 'Albania', code: 'AL' }],
  ['202', { name: 'Andorra', code: 'AD' }],
  ['203', { name: 'Austria', code: 'AT' }],
  ['204', { name: 'Portugal', code: 'PT' }],
  ['205', { name: 'Belgium', code: 'BE' }],
  ['206', { name: 'Belarus', code: 'BY' }],
  ['207', { name: 'Bulgaria', code: 'BG' }],
  ['208', { name: 'Vatican', code: 'VA' }],
  ['209', { name: 'Cyprus', code: 'CY' }],
  ['210', { name: 'Cyprus', code: 'CY' }],
  ['211', { name: 'Germany', code: 'DE' }],
  ['212', { name: 'Cyprus', code: 'CY' }],
  ['213', { name: 'Georgia', code: 'GE' }],
  ['214', { name: 'Moldova', code: 'MD' }],
  ['215', { name: 'Malta', code: 'MT' }],
  ['216', { name: 'Armenia', code: 'AM' }],
  ['218', { name: 'Germany', code: 'DE' }],
  ['219', { name: 'Denmark', code: 'DK' }],
  ['220', { name: 'Denmark', code: 'DK' }],
  ['224', { name: 'Spain', code: 'ES' }],
  ['225', { name: 'Spain', code: 'ES' }],
  ['226', { name: 'France', code: 'FR' }],
  ['227', { name: 'France', code: 'FR' }],
  ['228', { name: 'France', code: 'FR' }],
  ['229', { name: 'Malta', code: 'MT' }],
  ['230', { name: 'Finland', code: 'FI' }],
  ['231', { name: 'Faroe Is', code: 'FO' }],
  ['232', { name: 'United Kingdom', code: 'GB' }],
  ['233', { name: 'United Kingdom', code: 'GB' }],
  ['234', { name: 'United Kingdom', code: 'GB' }],
  ['235', { name: 'United Kingdom', code: 'GB' }],
  ['236', { name: 'Gibraltar', code: 'GI' }],
  ['237', { name: 'Greece', code: 'GR' }],
  ['238', { name: 'Croatia', code: 'HR' }],
  ['239', { name: 'Greece', code: 'GR' }],
  ['240', { name: 'Greece', code: 'GR' }],
  ['241', { name: 'Greece', code: 'GR' }],
  ['242', { name: 'Morocco', code: 'MA' }],
  ['243', { name: 'Hungary', code: 'HU' }],
  ['244', { name: 'Netherlands', code: 'NL' }],
  ['245', { name: 'Netherlands', code: 'NL' }],
  ['246', { name: 'Netherlands', code: 'NL' }],
  ['247', { name: 'Italy', code: 'IT' }],
  ['248', { name: 'Malta', code: 'MT' }],
  ['249', { name: 'Malta', code: 'MT' }],
  ['250', { name: 'Ireland', code: 'IE' }],
  ['251', { name: 'Iceland', code: 'IS' }],
  ['252', { name: 'Liechtenstein', code: 'LI' }],
  ['253', { name: 'Luxembourg', code: 'LU' }],
  ['254', { name: 'Monaco', code: 'MC' }],
  ['255', { name: 'Portugal', code: 'PT' }],
  ['256', { name: 'Malta', code: 'MT' }],
  ['257', { name: 'Norway', code: 'NO' }],
  ['258', { name: 'Norway', code: 'NO' }],
  ['259', { name: 'Norway', code: 'NO' }],
  ['261', { name: 'Poland', code: 'PL' }],
  ['262', { name: 'Montenegro', code: 'ME' }],
  ['263', { name: 'Portugal', code: 'PT' }],
  ['264', { name: 'Romania', code: 'RO' }],
  ['265', { name: 'Sweden', code: 'SE' }],
  ['266', { name: 'Sweden', code: 'SE' }],
  ['267', { name: 'Slovakia', code: 'SK' }],
  ['268', { name: 'San Marino', code: 'SM' }],
  ['269', { name: 'Switzerland', code: 'CH' }],
  ['270', { name: 'Czech Republic', code: 'CZ' }],
  ['271', { name: 'Turkey', code: 'TR' }],
  ['272', { name: 'Ukraine', code: 'UA' }],
  ['273', { name: 'Russia', code: 'RU' }],
  ['274', { name: 'FYR Macedonia', code: 'MK' }],
  ['275', { name: 'Latvia', code: 'LV' }],
  ['276', { name: 'Estonia', code: 'EE' }],
  ['277', { name: 'Lithuania', code: 'LT' }],
  ['278', { name: 'Slovenia', code: 'SI' }],
  ['279', { name: 'Serbia', code: 'RS' }],
  ['301', { name: 'Anguilla', code: 'AI' }],
  ['303', { name: 'USA', code: 'US' }],
  ['304', { name: 'Antigua Barbuda', code: 'AG' }],
  ['305', { name: 'Antigua Barbuda', code: 'AG' }],
  ['306', { name: 'Curacao', code: 'CW' }],
  ['307', { name: 'Aruba', code: 'AW' }],
  ['308', { name: 'Bahamas', code: 'BS' }],
  ['309', { name: 'Bahamas', code: 'BS' }],
  ['310', { name: 'Bermuda', code: 'BM' }],
  ['311', { name: 'Bahamas', code: 'BS' }],
  ['312', { name: 'Belize', code: 'BZ' }],
  ['314', { name: 'Barbados', code: 'BB' }],
  ['316', { name: 'Canada', code: 'CA' }],
  ['319', { name: 'Cayman Is', code: 'KY' }],
  ['321', { name: 'Costa Rica', code: 'CR' }],
  ['323', { name: 'Cuba', code: 'CU' }],
  ['325', { name: 'Dominica', code: 'DM' }],
  ['327', { name: 'Dominican Rep', code: 'DO' }],
  ['329', { name: 'Guadeloupe', code: 'GP' }],
  ['330', { name: 'Grenada', code: 'GD' }],
  ['331', { name: 'Greenland', code: 'GL' }],
  ['332', { name: 'Guatemala', code: 'GT' }],
  ['334', { name: 'Honduras', code: 'HN' }],
  ['336', { name: 'Haiti', code: 'HT' }],
  ['338', { name: 'USA', code: 'US' }],
  ['339', { name: 'Jamaica', code: 'JM' }],
  ['341', { name: 'St Kitts Nevis', code: 'KN' }],
  ['343', { name: 'St Lucia', code: 'LC' }],
  ['345', { name: 'Mexico', code: 'MX' }],
  ['347', { name: 'Martinique', code: 'MQ' }],
  ['348', { name: 'Montserrat', code: 'MS' }],
  ['350', { name: 'Nicaragua', code: 'NI' }],
  ['351', { name: 'Panama', code: 'PA' }],
  ['352', { name: 'Panama', code: 'PA' }],
  ['353', { name: 'Panama', code: 'PA' }],
  ['354', { name: 'Panama', code: 'PA' }],
  ['355', { name: 'Panama', code: 'PA' }],
  ['356', { name: 'Panama', code: 'PA' }],
  ['357', { name: 'Panama', code: 'PA' }],
  ['358', { name: 'Puerto Rico', code: 'PR' }],
  ['359', { name: 'El Salvador', code: 'SV' }],
  ['361', { name: 'St Pierre Miquelon', code: 'PM' }],
  ['362', { name: 'Trinidad Tobago', code: 'TT' }],
  ['364', { name: 'Turks Caicos Is', code: 'TC' }],
  ['366', { name: 'USA', code: 'US' }],
  ['367', { name: 'USA', code: 'US' }],
  ['368', { name: 'USA', code: 'US' }],
  ['369', { name: 'USA', code: 'US' }],
  ['370', { name: 'Panama', code: 'PA' }],
  ['371', { name: 'Panama', code: 'PA' }],
  ['372', { name: 'Panama', code: 'PA' }],
  ['373', { name: 'Panama', code: 'PA' }],
  ['374', { name: 'Panama', code: 'PA' }],
  ['375', { name: 'St Vincent Grenadines', code: 'VC' }],
  ['376', { name: 'St Vincent Grenadines', code: 'VC' }],
  ['377', { name: 'St Vincent Grenadines', code: 'VC' }],
  ['378', { name: 'British Virgin Is', code: 'VG' }],
  ['379', { name: 'US Virgin Is', code: 'VI' }],
  ['401', { name: 'Afghanistan', code: 'AF' }],
  ['403', { name: 'Saudi Arabia', code: 'SA' }],
  ['405', { name: 'Bangladesh', code: 'BD' }],
  ['408', { name: 'Bahrain', code: 'BH' }],
  ['410', { name: 'Bhutan', code: 'BT' }],
  ['412', { name: 'China', code: 'CN' }],
  ['413', { name: 'China', code: 'CN' }],
  ['414', { name: 'China', code: 'CN' }],
  ['416', { name: 'Taiwan', code: 'TW' }],
  ['417', { name: 'Sri Lanka', code: 'LK' }],
  ['419', { name: 'India', code: 'IN' }],
  ['422', { name: 'Iran', code: 'IR' }],
  ['423', { name: 'Azerbaijan', code: 'AZ' }],
  ['425', { name: 'Iraq', code: 'IQ' }],
  ['428', { name: 'Israel', code: 'IL' }],
  ['431', { name: 'Japan', code: 'JP' }],
  ['432', { name: 'Japan', code: 'JP' }],
  ['434', { name: 'Turkmenistan', code: 'TM' }],
  ['436', { name: 'Kazakhstan', code: 'KZ' }],
  ['437', { name: 'Uzbekistan', code: 'UZ' }],
  ['438', { name: 'Jordan', code: 'JO' }],
  ['440', { name: 'Korea', code: 'KR' }],
  ['441', { name: 'Korea', code: 'KR' }],
  ['443', { name: 'Palestine', code: 'PS' }],
  ['445', { name: 'DPR Korea', code: 'KP' }],
  ['447', { name: 'Kuwait', code: 'KW' }],
  ['450', { name: 'Lebanon', code: 'LB' }],
  ['451', { name: 'Kyrgyz Republic', code: 'KG' }],
  ['453', { name: 'Macao', code: 'MO' }],
  ['455', { name: 'Maldives', code: 'MV' }],
  ['457', { name: 'Mongolia', code: 'MN' }],
  ['459', { name: 'Nepal', code: 'NP' }],
  ['461', { name: 'Oman', code: 'OM' }],
  ['463', { name: 'Pakistan', code: 'PK' }],
  ['466', { name: 'Qatar', code: 'QA' }],
  ['468', { name: 'Syria', code: 'SY' }],
  ['470', { name: 'UAE', code: 'AE' }],
  ['471', { name: 'UAE', code: 'AE' }],
  ['472', { name: 'Tajikistan', code: 'TJ' }],
  ['473', { name: 'Yemen', code: 'YE' }],
  ['475', { name: 'Yemen', code: 'YE' }],
  ['477', { name: 'Hong Kong', code: 'HK' }],
  ['478', { name: 'Bosnia and Herzegovina', code: 'BA' }],
  ['501', { name: 'Antarctica', code: 'AQ' }],
  ['503', { name: 'Australia', code: 'AU' }],
  ['506', { name: 'Myanmar', code: 'MM' }],
  ['508', { name: 'Brunei', code: 'BN' }],
  ['510', { name: 'Micronesia', code: 'FM' }],
  ['511', { name: 'Palau', code: 'PW' }],
  ['512', { name: 'New Zealand', code: 'NZ' }],
  ['514', { name: 'Cambodia', code: 'KH' }],
  ['515', { name: 'Cambodia', code: 'KH' }],
  ['516', { name: 'Christmas Is', code: 'CX' }],
  ['518', { name: 'Cook Is', code: 'CK' }],
  ['520', { name: 'Fiji', code: 'FJ' }],
  ['523', { name: 'Cocos Is', code: 'CC' }],
  ['525', { name: 'Indonesia', code: 'ID' }],
  ['529', { name: 'Kiribati', code: 'KI' }],
  ['531', { name: 'Laos', code: 'LA' }],
  ['533', { name: 'Malaysia', code: 'MY' }],
  ['536', { name: 'N Mariana Is', code: 'MP' }],
  ['538', { name: 'Marshall Is', code: 'MH' }],
  ['540', { name: 'New Caledonia', code: 'NC' }],
  ['542', { name: 'Niue', code: 'NU' }],
  ['544', { name: 'Nauru', code: 'NR' }],
  ['546', { name: 'French Polynesia', code: 'PF' }],
  ['548', { name: 'Philippines', code: 'PH' }],
  ['553', { name: 'Papua New Guinea', code: 'PG' }],
  ['555', { name: 'Pitcairn Is', code: 'PN' }],
  ['557', { name: 'Solomon Is', code: 'SB' }],
  ['559', { name: 'American Samoa', code: 'AS' }],
  ['561', { name: 'Samoa', code: 'WS' }],
  ['563', { name: 'Singapore', code: 'SG' }],
  ['564', { name: 'Singapore', code: 'SG' }],
  ['565', { name: 'Singapore', code: 'SG' }],
  ['566', { name: 'Singapore', code: 'SG' }],
  ['567', { name: 'Thailand', code: 'TH' }],
  ['570', { name: 'Tonga', code: 'TO' }],
  ['572', { name: 'Tuvalu', code: 'TV' }],
  ['574', { name: 'Vietnam', code: 'VN' }],
  ['576', { name: 'Vanuatu', code: 'VU' }],
  ['577', { name: 'Vanuatu', code: 'VU' }],
  ['578', { name: 'Wallis Futuna Is', code: 'WF' }],
  ['601', { name: 'South Africa', code: 'ZA' }],
  ['603', { name: 'Angola', code: 'AO' }],
  ['605', { name: 'Algeria', code: 'DZ' }],
  ['607', { name: 'St Paul Amsterdam Is', code: 'TF' }],
  ['608', { name: 'Ascension Is', code: 'IO' }],
  ['609', { name: 'Burundi', code: 'BI' }],
  ['610', { name: 'Benin', code: 'BJ' }],
  ['611', { name: 'Botswana', code: 'BW' }],
  ['612', { name: 'Cen Afr Rep', code: 'CF' }],
  ['613', { name: 'Cameroon', code: 'CM' }],
  ['615', { name: 'Congo', code: 'CG' }],
  ['616', { name: 'Comoros', code: 'KM' }],
  ['617', { name: 'Cape Verde', code: 'CV' }],
  ['618', { name: 'Antarctica', code: 'AQ' }],
  ['619', { name: 'Ivory Coast', code: 'CI' }],
  ['620', { name: 'Comoros', code: 'KM' }],
  ['621', { name: 'Djibouti', code: 'DJ' }],
  ['622', { name: 'Egypt', code: 'EG' }],
  ['624', { name: 'Ethiopia', code: 'ET' }],
  ['625', { name: 'Eritrea', code: 'ER' }],
  ['626', { name: 'Gabon', code: 'GA' }],
  ['627', { name: 'Ghana', code: 'GH' }],
  ['629', { name: 'Gambia', code: 'GM' }],
  ['630', { name: 'Guinea-Bissau', code: 'GW' }],
  ['631', { name: 'Equ. Guinea', code: 'GQ' }],
  ['632', { name: 'Guinea', code: 'GN' }],
  ['633', { name: 'Burkina Faso', code: 'BF' }],
  ['634', { name: 'Kenya', code: 'KE' }],
  ['635', { name: 'Antarctica', code: 'AQ' }],
  ['636', { name: 'Liberia', code: 'LR' }],
  ['637', { name: 'Liberia', code: 'LR' }],
  ['642', { name: 'Libya', code: 'LY' }],
  ['644', { name: 'Lesotho', code: 'LS' }],
  ['645', { name: 'Mauritius', code: 'MU' }],
  ['647', { name: 'Madagascar', code: 'MG' }],
  ['649', { name: 'Mali', code: 'ML' }],
  ['650', { name: 'Mozambique', code: 'MZ' }],
  ['654', { name: 'Mauritania', code: 'MR' }],
  ['655', { name: 'Malawi', code: 'MW' }],
  ['656', { name: 'Niger', code: 'NE' }],
  ['657', { name: 'Nigeria', code: 'NG' }],
  ['659', { name: 'Namibia', code: 'NA' }],
  ['660', { name: 'Reunion', code: 'RE' }],
  ['661', { name: 'Rwanda', code: 'RW' }],
  ['662', { name: 'Sudan', code: 'SD' }],
  ['663', { name: 'Senegal', code: 'SN' }],
  ['664', { name: 'Seychelles', code: 'SC' }],
  ['665', { name: 'St Helena', code: 'SH' }],
  ['666', { name: 'Somalia', code: 'SO' }],
  ['667', { name: 'Sierra Leone', code: 'SL' }],
  ['668', { name: 'Sao Tome Principe', code: 'ST' }],
  ['669', { name: 'Swaziland', code: 'SZ' }],
  ['670', { name: 'Chad', code: 'TD' }],
  ['671', { name: 'Togo', code: 'TG' }],
  ['672', { name: 'Tunisia', code: 'TN' }],
  ['674', { name: 'Tanzania', code: 'TZ' }],
  ['675', { name: 'Uganda', code: 'UG' }],
  ['676', { name: 'DR Congo', code: 'CD' }],
  ['677', { name: 'Tanzania', code: 'TZ' }],
  ['678', { name: 'Zambia', code: 'ZM' }],
  ['679', { name: 'Zimbabwe', code: 'ZW' }],
  ['701', { name: 'Argentina', code: 'AR' }],
  ['710', { name: 'Brazil', code: 'BR' }],
  ['720', { name: 'Bolivia', code: 'BO' }],
  ['725', { name: 'Chile', code: 'CL' }],
  ['730', { name: 'Colombia', code: 'CO' }],
  ['735', { name: 'Ecuador', code: 'EC' }],
  ['740', { name: 'UK', code: 'UK' }],
  ['745', { name: 'Guiana', code: 'GF' }],
  ['750', { name: 'Guyana', code: 'GY' }],
  ['755', { name: 'Paraguay', code: 'PY' }],
  ['760', { name: 'Peru', code: 'PE' }],
  ['765', { name: 'Suriname', code: 'SR' }],
  ['770', { name: 'Uruguay', code: 'UY' }],
  ['775', { name: 'Venezuela', code: 'VE' }],
]);
