export const mockFairwayCard = {
  fairwayCard: {
    id: 'vuosaari',
    name: { fi: 'Vuosaaren väylä', sv: 'Nordsjöleden', en: 'Vuosaari channel' },
    n2000HeightSystem: false,
    group: '2',
    modificationTimestamp: 1668180623000,
    fairways: [
      {
        id: 4921,
        name: { fi: 'Vuosaaren sataman väylä', sv: '', en: null },
        primary: false,
        startText: 'Vuosaaren väylältä',
        endText: 'Vuosaaren satama',
        lightingCode: '1',
        lighting: { fi: 'Valaistu', sv: 'Samma på svenska', en: null },
        sizing: { minimumTurningCircle: null, minimumWidth: null, additionalInformation: null, reserveWater: '1,3' },
        sizingVessels: [{ type: 'Konttialus', length: 280.0, width: 33.0, draft: 13.0 }],
        navigationLines: [
          {
            id: 247451,
            length: 173.0,
            typeCode: '1',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.2106698161, 60.208557129],
                [25.2085365206, 60.2096843284],
              ],
            },
          },
          {
            id: 248875,
            length: 245.0,
            typeCode: '1',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.2137010065, 60.2069555003],
                [25.2106698161, 60.208557129],
              ],
            },
          },
        ],
        areas: [
          {
            id: 247474,
            name: null,
            depth: 13.0,
            draft: 14.3,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null }],
            typeCode: 1,
          },
          {
            id: 247483,
            name: null,
            depth: 13.0,
            draft: 14.3,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null }],
            typeCode: 1,
          },
          {
            id: 247479,
            name: null,
            depth: 13.0,
            draft: 14.3,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [
              { fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null },
              { fairwayId: 4915, sizingSpeed: null, sizingSpeed2: null },
            ],
            typeCode: 1,
          },
          {
            id: 196667,
            name: null,
            depth: null,
            draft: 10.5,
            referenceLevel: 'MW2012',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null }],
            typeCode: 1,
          },
          {
            id: 245291,
            name: null,
            depth: null,
            draft: 10.5,
            referenceLevel: 'MW2012',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null }],
            typeCode: 1,
          },
          {
            id: 247533,
            name: null,
            depth: null,
            draft: 14.3,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null }],
            typeCode: 1,
          },
          {
            id: 153486,
            name: null,
            depth: null,
            draft: 4.5,
            referenceLevel: 'MW2012',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null }],
            typeCode: 1,
          },
          {
            id: 248957,
            name: null,
            depth: null,
            draft: 12.5,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null }],
            typeCode: 2,
          },
          {
            id: 248245,
            name: null,
            depth: null,
            draft: 12.5,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null }],
            typeCode: 2,
          },
          {
            id: 248250,
            name: null,
            depth: null,
            draft: 12.5,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null }],
            typeCode: 11,
          },
          {
            id: 248278,
            name: null,
            depth: null,
            draft: 12.5,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null }],
            typeCode: 4,
          },
          {
            id: 248285,
            name: null,
            depth: null,
            draft: 10.5,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null }],
            typeCode: 5,
          },
          {
            id: 248892,
            name: null,
            depth: null,
            draft: 10.5,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4921, sizingSpeed: null, sizingSpeed2: null }],
            typeCode: 15,
          },
        ],
      },
      {
        id: 4927,
        name: { fi: 'Vuosaaren väylä', sv: '', en: null },
        primary: true,
        startText: 'Suomenlahti, avomeri',
        endText: 'Vuosaaren satamaan',
        lightingCode: '1',
        lighting: { fi: 'Valaistu', sv: 'Samma på svenska', en: null },
        sizing: {
          minimumTurningCircle: 1400.0,
          minimumWidth: 200.0,
          additionalInformation: 'Huom. 2. mitoitusalus= Bulk-alus, Pituus (l) 210m, Leveys (b) 33,5m, Syväys13m',
          reserveWater: '2,0 - 2,5',
        },
        sizingVessels: [
          { type: 'Konttialus', length: 280.0, width: 33.0, draft: 13.0 },
          { type: 'Bulk-alus', length: 200.0, width: 28.0, draft: 11.0 },
          { type: 'Kuivalastialus', length: 250.0, width: 40.0, draft: 12.0 },
        ],
        navigationLines: [
          {
            id: 247383,
            length: 696.0,
            typeCode: '1',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.2178729734, 60.1816114432],
                [25.219896411, 60.187774077],
              ],
            },
          },
          {
            id: 247387,
            length: 1652.0,
            typeCode: '1',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.213071023, 60.1669767984],
                [25.2178729734, 60.1816114432],
              ],
            },
          },
          {
            id: 247391,
            length: 5892.0,
            typeCode: '1',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.1943564303, 60.1098126853],
                [25.1952217193, 60.1124602849],
                [25.2114405711, 60.1620047432],
              ],
            },
          },
          {
            id: 247395,
            length: 1072.0,
            typeCode: '1',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.1858306952, 60.1011857351],
                [25.191978489, 60.1074070298],
                [25.1943564303, 60.1098126853],
              ],
            },
          },
          {
            id: 247399,
            length: 16863.0,
            typeCode: '1',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.0354333305, 59.9481593584],
                [25.1610744644, 60.0760173012],
                [25.1689077651, 60.0839689046],
              ],
            },
          },
          {
            id: 247403,
            length: 2137.0,
            typeCode: '1',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.1689077651, 60.0839689046],
                [25.1858306952, 60.1011857351],
              ],
            },
          },
          {
            id: 247410,
            length: 561.0,
            typeCode: '1',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.2114405711, 60.1620047432],
                [25.213071023, 60.1669767984],
              ],
            },
          },
          {
            id: 247414,
            length: 839.0,
            typeCode: '1',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.219896411, 60.187774077],
                [25.2223367301, 60.1952032314],
              ],
            },
          },
          {
            id: 247438,
            length: 691.0,
            typeCode: '1',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.2223367301, 60.1952032314],
                [25.224349124, 60.2013270833],
              ],
            },
          },
          {
            id: 248872,
            length: 861.0,
            typeCode: '1',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.224349124, 60.2013270833],
                [25.2158027779, 60.2058447598],
                [25.2137010065, 60.2069555003],
              ],
            },
          },
          {
            id: 247442,
            length: 1284.0,
            typeCode: '3',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.2223367301, 60.1952032314],
                [25.2225855696, 60.196243363],
                [25.2226602739, 60.1972901529],
                [25.2225603282, 60.1983363872],
                [25.2222864212, 60.1993748568],
                [25.2218404404, 60.2003984066],
                [25.2212254591, 60.2013999851],
                [25.2204457152, 60.2023726927],
                [25.2195065818, 60.2033098292],
                [25.2184145306, 60.2042049402],
                [25.2171770869, 60.2050518611],
                [25.2158027779, 60.2058447598],
              ],
            },
          },
          {
            id: 247407,
            length: 593.0,
            typeCode: '4',
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            geometry: {
              coordinates: [
                [25.191978489, 60.1074070298],
                [25.1930671178, 60.1086221971],
                [25.1939736413, 60.109874018],
                [25.1946931426, 60.1111556989],
                [25.1952217193, 60.1124602849],
              ],
            },
          },
        ],
        areas: [
          {
            id: 246497,
            name: null,
            depth: 13.0,
            draft: 15.5,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: 15.0, sizingSpeed2: null }],
          },
          {
            id: 247457,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: 10.0, sizingSpeed2: 12.0 }],
          },
          {
            id: 247465,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: 7.0, sizingSpeed2: 10.0 }],
          },
          {
            id: 247488,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [
              { fairwayId: 4880, sizingSpeed: null, sizingSpeed2: null },
              { fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null },
            ],
          },
          {
            id: 248878,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null }],
          },
          {
            id: 249605,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [
              { fairwayId: 4865, sizingSpeed: null, sizingSpeed2: null },
              { fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null },
            ],
          },
          {
            id: 249619,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: 12.0, sizingSpeed2: 15.0 }],
          },
          {
            id: 246612,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null }],
          },
          {
            id: 249640,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null }],
          },
          {
            id: 247525,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [
              { fairwayId: 4880, sizingSpeed: null, sizingSpeed2: null },
              { fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null },
            ],
          },
          {
            id: 249633,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [
              { fairwayId: 4925, sizingSpeed: null, sizingSpeed2: null },
              { fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null },
            ],
          },
          {
            id: 249157,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null }],
          },
          {
            id: 246513,
            name: null,
            depth: 13.0,
            draft: 15.5,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null }],
          },
          {
            id: 247372,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null }],
          },
          {
            id: 246607,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null }],
          },
          {
            id: 248868,
            name: null,
            depth: 13.0,
            draft: 15.5,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null }],
          },
          {
            id: 246520,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null }],
          },
          {
            id: 246587,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [
              { fairwayId: 4925, sizingSpeed: null, sizingSpeed2: null },
              { fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null },
            ],
          },
          {
            id: 246591,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [{ fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null }],
          },
          {
            id: 246603,
            name: null,
            depth: 13.0,
            draft: 15.0,
            referenceLevel: 'MW2015',
            n2000depth: null,
            n2000draft: null,
            n2000ReferenceLevel: null,
            additionalInformation: null,
            fairways: [
              { fairwayId: 4880, sizingSpeed: null, sizingSpeed2: null },
              { fairwayId: 4927, sizingSpeed: null, sizingSpeed2: null },
            ],
          },
        ],
      },
    ],
    lineText: {
      fi: 'Linjoja 3, merkitty linjatauluin.',
      sv: 'Tre linjer, utmärkta med enstavlor.',
      en: 'Three lines marked with boards.',
    },
    anchorage: {
      fi: 'Väylän ulko-osalla ankkurointialue on Helsingin majakan luoteispuolella. Ankkuroinnissa on noudatettava luotsin tai VTS - keskuksen antamia ohjeita. Eestiluodon eteläpuolella ja Musta Hevosen länsipuolella on väylän levennysalueita.',
      sv: 'Ankringsområdet i angöringen ligger NV om Helsingfors fyr. Vid ankring bör lotsens eller VTS-centralens anvisningar följas. Farleden har breddade områden Söder om Estlotan och väster om Svarta Hästen.',
      en: 'In the approach there is an anchorage area NW of Helsinki Lighthouse. When anchoring the instructions given by the pilot or the VTS centre must be followed. Areas where the channel has been widened South of Eestiluoto and west of Musta Hevonen.',
    },
    generalInfo: {
      fi: 'Alusliikenteen järjestelemiseksi Vuosaaren satamasta lähteville aluksille on käytössä lähtölupamenettely.',
      sv: 'Regleringen av fartygstrafiken innebär ett förfarande med avgångstillstånd för fartyg som avgår från Nordsjö hamn.',
      en: 'The organization of vessel traffic departing from Vuosaari Harbour includes a procedure for issuing clearance for departure.',
    },
    navigationCondition: {
      fi: 'Väylän ulko-osalla väylä on avomerta ja suojaton E-S-W- tuulille. Eestiluodosta väylä jatkuu saarien ja karien suojaamana satamaan.',
      sv: 'Farledens yttre del är öppen sjö och oskyddad för O-S-V vind. Från Estlotan till hamnen löper farleden i skydd av holmar och skär.',
      en: 'The approach is at open sea and is unsheltered against E-S-W winds. From Eestiluoto to the harbour the channel is protected by islands and skerries.',
    },
    iceCondition: {
      fi: 'Jää ongelmia esiintyy yleensä vain satama-altaissa, joissa jääsohjo saattaa vaikeuttaa aluksen käsittelyä. Ajoittain ahtautumista saattaa esiintyä Eestiluodon etelä- ja pohjoispuoleisilla alueilla.',
      sv: 'Isproblem förekommer vanligen endast i hamnbassängerna, där issörja kan försvåra manövreringen. Tidvis vallbildning i områdena S och N om Estlotan.',
      en: 'Ice usually causes problems only in the harbour basins, where slush may make manoeuvring difficult. Occasional ice ridging in the areas S and N of Eestiluoto.',
    },
    attention: null,
    speedLimit: {
      fi: 'Talvikaudella (1.11 - 31.3) Vuosaaren väylän välillä Krokholmshället - Vuosaaren satama on voimassa vuosittain jatkuva nopeusrajoitus 24 km/h.',
      sv: 'Under vintersäsongen (1.11 - 31.3) är en fartbegränsning 24 km/h i kraft (I farleden) mellan Krokholmshället och Nordsjö hamn.',
      en: 'During the winter season (1 November - 31 March) a speed limit of 24/h will be in force (in the channel) between Krokholmshället and Vuosaari Harbour.',
    },
    visibility: {
      fi: 'Näkyvyyden tulee olla vähintään 300 m kaikilla aluksilla. Lisäksi yli 200 m:n pituiselle alukselle näkyvyyttä oltava vähintään 1,0 M.',
      sv: 'Bör vara minst 300 m för alla fartyg. Dessutom krävs minst 1,0 M sikt för fartyg med en längd över 200 m.',
      en: 'Minimum visibility for all vessels 300 m. Minimum visibility for vessels of more than 200 m in length, 1.0 nautical mile.',
    },
    windGauge: { fi: 'Harmajalla.', sv: 'På Gråhara.', en: 'At Harmaja.' },
    vesselRecommendation: {
      fi: 'Maksimisyvyydessä kulkevien alusten on nopeudessaan otettava huomioon matalikot ja nopeuspainuman vaikutus seuraavissa paikoissa: Svartbådanin kaakkoispuolella, Utön länsipuolella, Torvskärissä, välillä Länggaddin eteläpuoli - Gråskär, välillä Berghamn - Smörgrund - Kyrkfjärden, Lövskärissä sekä Airistolla kolmen 16,8 m matalan kohdalla.',
      sv: 'Fartyg med maximalt djupgående ska med avseende på hastigheten beakta grunden och fartens inverkan på följande platser: SO om Svartbådan, V om Utö, vid Torvskär, mellan S Länggadd och Gråskär, mellan Berghamn och Smörgrund och Kyrkfjärden, vid Lövskär samt i Erstan vid de tre grunden på 16,8 m.',
      en: 'Vessels with a draught close to the max. authorised draught are requested to beware of shoals and the causing of squat in the following areas: SE of Svartbådan, W of Utö, at Torvskär, between the southern part of Länggadd and Gråskär, between Berghamn and Smörgrund and Kyrkfjärden, at Lövskär and in Airisto at the three 16,8 m shoals.',
    },
    seaLevel: { fi: 'Kemi mareografi', sv: 'Kemi mareograf', en: 'Kemi mareograph' },
    windRecommendation: {
      fi: 'Yli 200 m:n pituisilla aluksilla maksimituulennopeus 15 m/s.',
      sv: 'Max. vindhastighet 15 m/s för fartyg med en längd av 200 m eller mera.',
      en: 'The maximum wind speed is 15 m/s for vessels over 200 m in length.',
    },
    trafficService: {
      pilot: {
        email: 'pilotorder.south@finnpilot.fi',
        extraInfo: {
          fi: 'Huom. Talviaikana tai huonolla säällä luotsipaikka sovittava erikseen. Luotsia seuraa yleensä avustava luotsi turvallisuussyistä.',
          sv: 'Obs. Vintertid och vid dåligt väder ska platsen där lots möter särskilt överenskommas. En annan lots bistår i allmänheten lotsen av säkerhetsskäl.',
          en: 'Note: During the winter season and by bad weather the pilot boarding position must be agreed on separately. Generally there is also, for safety reasons, another pilot assisting.',
        },
        phoneNumber: '+358207546151',
        fax: '+358207546161',
        internet: 'https://www.pilotonline.fi',
        places: [
          {
            id: 28.0,
            name: 'Vuosaari',
            pilotJourney: 9.0,
            geometry: { coordinates: [25.163167, 60.082667] },
          },
        ],
      },
      vts: [
        {
          name: { fi: 'Suomenlahden meriliikennekeskus', sv: 'Finska vikens sjötrafikcentral', en: 'Helsinki VTS' },
          vhf: [
            {
              channel: 71,
            },
          ],
          phoneNumber: '+358204485391',
          email: ['helsinki.vts@fintraffic.fi', 'supervisors.hki@fintraffic.fi'],
        },
      ],
      tugs: [
        {
          name: {
            fi: 'Yksityiset hinaajat tarvittaessa.',
            sv: 'Privata bogserbåtar vid behov.',
            en: 'Privately owned tugs available.',
          },
          email: 'testi@testi.com',
          phoneNumber: ['+35810123456789'],
          fax: '+3581234567890',
        },
      ],
    },
    harbors: [
      {
        quays: [
          {
            id: '1',
            name: { fi: 'A laituri', sv: 'A kajen', en: 'Quay A' },
            length: 180.0,
            sections: [{ name: null, depth: 12.5 }],
            extraInfo: { fi: 'säädettävä ramppi', sv: 'justerbar ramp', en: 'adjustable ramp' },
            geometry: { type: 'Point', coordinates: [25.19323465568021, 60.21030442526192] },
          },
          {
            id: '2',
            name: { fi: 'AP pistolaituri', sv: 'AP kajen (pir)', en: 'Quay AP (pier)' },
            length: 215.0,
            sections: [
              { name: null, depth: 10.5 },
              { name: null, depth: 12.5 },
            ],
            extraInfo: { fi: '2 kpl kiinteää ramppia', sv: '2 fasta ramper', en: '2 fixed ramps' },
            geometry: { type: 'Point', coordinates: [25.19473180480529, 60.20955125229692] },
          },
          {
            id: '3',
            name: { fi: 'BP pistolaituri', sv: 'BP kajen (pir)', en: 'Quay BP (pier)' },
            length: 250.0,
            sections: [{ name: null, depth: 12.5 }],
            extraInfo: { fi: '2 kpl kiinteää ramppia', sv: '2 fasta ramper', en: '2 fixed ramps' },
            geometry: { type: 'Point', coordinates: [25.189489375700667, 60.21558232946173] },
          },
          {
            id: '4',
            name: { fi: 'CP pistolaituri', sv: 'CP kajen (pir)', en: 'Quay CP (pier)' },
            length: 250.0,
            sections: [{ name: null, depth: 10.5 }],
            extraInfo: { fi: '2 kpl säädettävää tuplaramppia', sv: '2 justerbara dubbelramper', en: '2 adjustable ramps' },
            geometry: { type: 'Point', coordinates: [25.199991979381792, 60.218917742690294] },
          },
          {
            id: '5',
            name: { fi: 'D laituri', sv: 'D kajen', en: 'Quay D' },
            length: 750.0,
            sections: [
              { name: null, depth: 12.5 },
              { name: null, depth: 14.3 },
            ],
            extraInfo: {
              fi: 'konttialuksille, 1 kiinteä ramppi',
              sv: 'containerfartyg, fast ramp',
              en: 'containers, fixed ramp',
            },
            geometry: { type: 'Point', coordinates: [25.19037552074544, 60.213384247190206] },
          },
          {
            id: '6',
            name: { fi: 'E laituri', sv: 'E kajen', en: 'Quay E' },
            length: 750.0,
            sections: [
              { name: null, depth: 12.5 },
              { name: null, depth: 14.3 },
            ],
            extraInfo: {
              fi: 'konttialuksille, 1 kiinteä ramppi',
              sv: 'containerfartyg, fast ramp',
              en: 'containers, fixed ramp',
            },
            geometry: { type: 'Point', coordinates: [25.193576012449466, 60.214864489604146] },
          },
          {
            id: '7',
            name: { fi: 'F laituri', sv: 'F kajen', en: 'Quay F' },
            length: 497.0,
            sections: [
              { name: null, depth: 10.5 },
              { name: null, depth: 14.3 },
            ],
            extraInfo: { fi: '2 kpl kiinteää ramppia', sv: '2 fasta ramper', en: '2 fixed ramps' },
            geometry: { type: 'Point', coordinates: [25.19826034595303, 60.217641803529204] },
          },
          {
            id: '8',
            name: { fi: 'VG9 laituri', sv: 'VG9 kajen', en: 'Quay VG9' },
            length: 162.0,
            sections: [{ name: null, depth: 12.5 }],
            extraInfo: { fi: '1 kiinteä ramppi', sv: 'fast ramp', en: 'fixed ramp' },
            geometry: { type: 'Point', coordinates: [25.19961921791056, 60.21401347543198] },
          },
          {
            id: '9',
            name: { fi: 'GP 1 pistolaituri', sv: 'GP 1 kajen (pir)', en: 'Quay GP 1 (pier)' },
            length: 204.0,
            sections: [{ name: null, depth: 12.5 }],
            extraInfo: { fi: '2 kpl kiinteää ramppia', sv: '2 fasta ramper', en: '2 fixed ramps' },
            geometry: { type: 'Point', coordinates: [25.202402425482397, 60.21365830752661] },
          },
          {
            id: '10',
            name: { fi: 'GP 2 pistolaituri', sv: 'GP 2 kajen (pir)', en: 'Quay GP 2 (pier)' },
            length: 204.0,
            sections: [
              { name: null, depth: 12.5 },
              { name: null, depth: 14.3 },
            ],
            extraInfo: { fi: '2 kpl kiinteää ramppia', sv: '2 fasta ramper', en: '2 fixed ramps' },
            geometry: { type: 'Point', coordinates: [25.20380171410149, 60.2142420858206] },
          },
          {
            id: '11',
            name: { fi: 'VGA laituri', sv: 'VGA kajen', en: 'Quay VGA' },
            length: 189.0,
            sections: [{ name: null, depth: 14.3 }],
            extraInfo: null,
            geometry: { type: 'Point', coordinates: [25.199142678660635, 60.212803690896315] },
          },
        ],
        id: 'harbor1',
        name: { fi: 'Helsingin Satama Oy, Helsinki', sv: 'Helsingfors Hamn, Helsingfors', en: 'Port of Helsinki, Helsinki' },
        phoneNumber: ['+35893101621'],
        fax: '+358931033802',
        email: 'port.helsinki@portofhelsinki.fi',
        internet: 'https://www.portofhelsinki.fi/',
        extraInfo: null,
        harborBasin: {
          fi: 'Kääntöympyrän halkaisija 400 m, ankkurin käyttö sallittu. Ankkurin käyttö kielletty 10 m sisällä laiturin reunasta',
          sv: 'Svängcirkelns diameter 400 m, tillåtet att använda ankare. Förbjudet att använda ankare 10 m från kaj.',
          en: 'Diameter of turning circle 400 m, use of anchor permitted. Use of anchor prohibited 10 m from quay.',
        },
        cargo: [
          {
            fi: 'D laituri: 2 konttinosturia, nostokyky 50/60 tn, ulottuma 38 m; 2 konttinosturia, nostokyky 40/50 tn, ulottuma 27 m',
            sv: 'D kajen: 2 containerkranar, lyftkapacitet 50/60 t, räckvidd 38 m; 2 containerkranar, lyftkapacitet 40/50 t, räckvidd 27 m',
            en: 'Quay D: 2 container cranes, lifting capacity 50/60 t, outreach 38 m; 2 container cranes, lifting capacity 40/50 t, outreach 27m',
          },
          {
            fi: 'E laituri: 4 konttinosturia, nostokyky 65/90 tn, ulottuvuus 46 m',
            sv: 'E kajen: 4 containerkranar, lyftkapacitet 65/90 t, räckvidd 46 m',
            en: 'Quay E: 4 container cranes, lifting capacity 65/90 t, outreach 46 m',
          },
          {
            fi: 'F laituri: konttinosturi, nostokyky 40/50 tn, ulottuma 34 m',
            sv: 'F kajen: containerkran, lyftkapacitet 40/50 t, räckvidd 34 m',
            en: 'Quay F: container crane, lifting capacity 40/50 t, outreach 34 m',
          },
        ],
      },
    ],
  },
};

export const mockFairwayList = {
  fairwayCards: [
    {
      id: 'hanko',
      name: { fi: 'Hangon meriväylä', sv: 'Hangö havsfarled', en: 'Hanko channel' },
      modificationTimestamp: 1667808284000,
      group: '1',
      n2000HeightSystem: false,
      fairways: [],
    },
    {
      id: 'uusikaupunki',
      name: { fi: 'Uudenkaupungin väylä', sv: '[sv] Uudenkaupungin väylä', en: 'Uusikaupunki channel' },
      modificationTimestamp: 1667808285000,
      group: '1',
      n2000HeightSystem: false,
      fairways: [],
    },
    {
      id: 'saimaa',
      name: { fi: 'Saimaan väylä', sv: 'Saimaan väylä', en: 'Saimaan väylä' },
      modificationTimestamp: 1667808285000,
      group: '3',
      n2000HeightSystem: false,
      fairways: [],
    },
    {
      id: 'helsinki',
      name: { fi: 'Helsingin väylä', sv: 'Helsingforsleden', en: 'Helsinki channel' },
      modificationTimestamp: 1667808284000,
      group: '2',
      n2000HeightSystem: false,
      fairways: [],
    },
    {
      id: 'utohanko',
      name: { fi: 'Utö-Hanko väylä', sv: 'Farleden Utö-Hangö', en: 'Utö-Hanko channel' },
      modificationTimestamp: 1667808284000,
      group: '1',
      n2000HeightSystem: false,
      fairways: [],
    },
    {
      id: 'kemi',
      name: { fi: '', sv: '[sv] Kemin väylä', en: 'Kemi Ajos fairway' },
      modificationTimestamp: 1667808284000,
      group: '3',
      n2000HeightSystem: true,
      fairways: [],
    },
    {
      id: 'naantali',
      name: { fi: 'Naantalin väylä', sv: 'Farleden Nådendal', en: 'Naantali channel' },
      modificationTimestamp: 1667808285000,
      group: '1',
      n2000HeightSystem: false,
      fairways: [],
    },
    mockFairwayCard.fairwayCard,
  ],
};
